#ifndef THESIS_PSEUDO_RANDOM_SEQUENCES_MILLER_RABINPRIMALITYTEST_H
#define THESIS_PSEUDO_RANDOM_SEQUENCES_MILLER_RABINPRIMALITYTEST_H
#include <stdint.h>

bool IsPrime(const uint64_t n, const int k);
#endif //THESIS_PSEUDO_RANDOM_SEQUENCES_MILLER_RABINPRIMALITYTEST_H
